export const BookItems = [
  {
    id: 1,
    role: 'like',
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 10',
    author: '김땡땡',
    publish: '잼나책방',
    startDate: null,
    endDate: null,
  },
  {
    id: 2,
    role: 'like',
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 11',
    author: '이땡떙',
    publish: '잼나책방',
    startDate: null,
    endDate: null,
  },
  {
    id: 3,
    role: 'like',
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 12',
    author: '한땡땡',
    publish: '잼나책방',
    startDate: null,
    endDate: null,
  },
  {
    id: 4,
    role: 'read',
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 17',
    author: '유땡땡',
    publish: '잼나책방',
    startDate: '2022.03.27',
    endDate: null,
  },
  {
    id: 5,
    role: 'read',
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름',
    author: '미땡땡',
    publish: '잼나책방',
    startDate: '2022.03.30',
    endDate: null,
  },
  {
    id: 6,
    role: 'done',
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 100',
    author: '박땡땡',
    publish: '잼나책방',
    startDate: '2022.03.21',
    endDate: '2022.03.28',
  },
];
