export const ReviewItems = [
  {
    id: 1,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 1',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 2,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 2',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 3,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 3',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 4,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 4',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 5,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 5',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 6,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 6',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 7,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 7',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 8,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 8',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 9,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 9',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 10,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 10',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 11,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 11',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 12,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 12',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 13,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 13',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 14,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 14',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 15,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 15',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 16,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 16',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 17,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 17',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 18,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 18',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 19,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 19',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 20,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 20',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 21,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 21',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 22,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 22',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 23,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 23',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 24,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 24',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 25,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 25',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 26,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 26',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 27,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 27',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 28,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 28',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 29,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 29',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 30,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 30',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 31,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 31',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 32,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 32',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 33,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 33',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 34,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 34',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 35,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 35',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 36,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 36',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 37,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 37',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 38,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 38',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 39,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 39',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 40,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 40',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 41,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 41',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 42,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 42',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 43,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 43',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 44,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 44',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 45,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 45',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 46,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 46',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 47,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 47',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 48,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 48',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 49,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 49',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 50,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 50',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 51,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 51',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 52,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 52',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 53,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 53',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 54,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 54',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 55,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 55',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 56,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 56',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 57,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 57',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 58,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 58',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 59,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 59',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 60,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 60',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 61,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 61',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 62,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 62',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 63,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 63',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 64,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 64',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 65,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 65',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 66,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 66',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 67,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 67',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 68,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 68',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 69,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 69',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 70,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 70',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 71,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 71',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 72,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 72',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 73,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 73',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 74,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 74',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
  {
    id: 75,
    img: `${process.env.PUBLIC_URL}/assets/main-bestlist-book.png`,
    title: '책이름 75',
    author: '김땡땡',
    rating: 9.8,
    total: 21,
  },
];
